import unknown from "../assets/img/gatos/unknown.jpg";

export const gatosEuropeo = [
    {
        name: "",
        gender: "",
        birth: "2026-08-24",
        img: unknown.src,
        img2: unknown.src,
        alt: "Camada de gatos persas europeos",
        color: "Blanco",
        disponibleEstilo: "absolute top-4 right-4 bg-green-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg",
        disponibleTexto: "✓ Disponible",
    },
    {
        name: "",
        gender: "",
        birth: "2026-08-24",
        img: unknown.src,
        img2: unknown.src,
        alt: "Camada de gatos persas europeos",
        color: "Blanco",
        disponibleEstilo: "absolute top-4 right-4 bg-green-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg",
        disponibleTexto: "✓ Disponible",
    },
    {
        name: "",
        gender: "",
        birth: "2026-08-24",
        img: unknown.src,
        img2: unknown.src,
        alt: "Camada de gatos persas europeos",
        color: "Blanco",
        disponibleEstilo: "absolute top-4 right-4 bg-green-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg",
        disponibleTexto: "✓ Disponible",
    },
    {
        name: "",
        gender: "",
        birth: "2026-08-24",
        img: unknown.src,
        img2: unknown.src,
        alt: "Camada de gatos persas europeos",
        color: "Blanco",
        disponibleEstilo: "absolute top-4 right-4 bg-green-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg",
        disponibleTexto: "✓ Disponible",
    },
    {
        name: "",
        gender: "",
        birth: "2026-08-24",
        img: unknown.src,
        img2: unknown.src,
        alt: "Camada de gatos persas europeos",
        color: "Atigrado",
        disponibleEstilo: "absolute top-4 right-4 bg-green-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg",
        disponibleTexto: "✓ Disponible",
    },
    {
        name: "",
        gender: "",
        birth: "2026-08-24",
        img: unknown.src,
        img2: unknown.src,
        alt: "Camada de gatos persas europeos",
        color: "Atigrado",
        disponibleEstilo: "absolute top-4 right-4 bg-green-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg",
        disponibleTexto: "✓ Disponible",
    },
];